# SPDX-License-Identifier: Apache-2.0
# umoci: Umoci Modifies Open Containers' Images
# Copyright (C) 2016-2025 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM golang:latest

RUN apt-get update && apt-get install -y clang

RUN go get -u github.com/dvyukov/go-fuzz/go-fuzz \
	github.com/dvyukov/go-fuzz/go-fuzz-dep \
	github.com/dvyukov/go-fuzz/go-fuzz-build

COPY . $GOPATH/src/github.com/opencontainers/umoci

WORKDIR $GOPATH/src/github.com/opencontainers/umoci

RUN go clean --modcache && \
    go mod tidy && \
    go mod vendor && \
    rm -r ./vendor

